export const splashGetImgSrc = 'Splash/getImgSrc'
export const latestGetStories = 'Latest/getStories'
export const beforeGetStories = 'Before/getStories'
export const themesGetList = 'Themes/getList'
export const themesGetContent = 'Themes/getContent'
export const detailGetNews = 'Detail/getNews'
